/* Generated Code */
// scalastyle:off
package models.engine.rdbms.functions

import models.engine.DatabaseEngine

trait SQLServerFunctions extends DatabaseEngine {
  override val builtInFunctions = Seq(
    "abs",
    "acos",
    "ascii",
    "asin",
    "atan",
    "avg",
    "bit_length",
    "cast",
    "ceiling",
    "char",
    "coalesce",
    "concat",
    "cos",
    "cot",
    "count",
    "current_date",
    "current_time",
    "current_timestamp",
    "datename",
    "day",
    "degrees",
    "exp",
    "extract",
    "floor",
    "getdate",
    "getutcdate",
    "hour",
    "isnull",
    "len",
    "length",
    "locate",
    "log",
    "log10",
    "lower",
    "ltrim",
    "max",
    "min",
    "minute",
    "mod",
    "month",
    "nullif",
    "pi",
    "radians",
    "rand",
    "reverse",
    "round",
    "row_number",
    "rtrim",
    "second",
    "sign",
    "sin",
    "space",
    "sqrt",
    "square",
    "str",
    "substring",
    "sum",
    "tan",
    "trim",
    "upper",
    "user",
    "year"
  )
}
// scalastyle:on
