/* Generated Code */
// scalastyle:off
package models.engine.rdbms

import models.engine.DatabaseEngine

object DB2 extends DatabaseEngine(
  id = "db2",
  name = "DB2",
  driverClass = "com.ibm.db2.jcc.DB2Driver",
  exampleUrl = "jdbc:db2://hostname:50000/database",

  builtInFunctions = Seq(
    "abs",
    "absval",
    "acos",
    "asin",
    "atan",
    "avg",
    "bigint",
    "bit_length",
    "cast",
    "ceil",
    "ceiling",
    "char",
    "chr",
    "coalesce",
    "concat",
    "cos",
    "cot",
    "count",
    "current_date",
    "current_time",
    "current_timestamp",
    "date",
    "day",
    "dayname",
    "dayofweek",
    "dayofweek_iso",
    "dayofyear",
    "days",
    "degrees",
    "digits",
    "double",
    "exp",
    "extract",
    "float",
    "floor",
    "hex",
    "hour",
    "integer",
    "julian_day",
    "lcase",
    "length",
    "ln",
    "locate",
    "log",
    "log10",
    "lower",
    "ltrim",
    "max",
    "microsecond",
    "midnight_seconds",
    "min",
    "minute",
    "mod",
    "month",
    "monthname",
    "nullif",
    "posstr",
    "quarter",
    "radians",
    "rand",
    "real",
    "round",
    "rtrim",
    "second",
    "sign",
    "sin",
    "smallint",
    "soundex",
    "sqrt",
    "stddev",
    "str",
    "substr",
    "substring",
    "sum",
    "tan",
    "time",
    "timestamp",
    "timestamp_iso",
    "trim",
    "ucase",
    "upper",
    "varchar",
    "variance",
    "week",
    "week_iso",
    "year"
  ),

  columnTypes = Seq(
    "bigint",
    "varchar",
    "smallint",
    "blob",
    "smallint",
    "char",
    "clob",
    "date",
    "double",
    "float",
    "integer",
    "nvarchar",
    "long varchar for bit data",
    "long varchar",
    "nchar",
    "nclob",
    "numeric",
    "nvarchar",
    "real",
    "smallint",
    "time",
    "timestamp",
    "smallint",
    "varchar",
    "varchar"
  )
) {
  override val leftQuoteIdentifier = "\""
  override val rightQuoteIdentifier = "\""
}
// scalastyle:on
