/* Generated Code */
// scalastyle:off
package models.engine.rdbms

import models.engine.DatabaseEngine

object MySQL extends DatabaseEngine(
  id = "mysql",
  name = "MySQL",
  driverClass = "com.mysql.jdbc.Driver",
  exampleUrl = "jdbc:mysql://localhost/test",

  builtInFunctions = Seq(
    "abs",
    "acos",
    "ascii",
    "asin",
    "atan",
    "avg",
    "bin",
    "bit_count",
    "bit_length",
    "cast",
    "ceil",
    "ceiling",
    "char_length",
    "character_length",
    "coalesce",
    "concat",
    "cos",
    "cot",
    "count",
    "crc32",
    "curdate",
    "current_date",
    "current_time",
    "current_timestamp",
    "curtime",
    "date",
    "date_format",
    "datediff",
    "day",
    "dayname",
    "dayofmonth",
    "dayofweek",
    "dayofyear",
    "degrees",
    "encrypt",
    "exp",
    "extract",
    "floor",
    "from_days",
    "from_unixtime",
    "hex",
    "hour",
    "last_day",
    "lcase",
    "length",
    "ln",
    "localtime",
    "localtimestamp",
    "locate",
    "log",
    "log10",
    "log2",
    "lower",
    "ltrim",
    "max",
    "md5",
    "microseconds",
    "min",
    "minute",
    "mod",
    "month",
    "monthname",
    "now",
    "nullif",
    "oct",
    "octet_length",
    "ord",
    "pi",
    "quarter",
    "quote",
    "radians",
    "rand",
    "reverse",
    "round",
    "rtrim",
    "sec_to_time",
    "second",
    "sha",
    "sha1",
    "sign",
    "sin",
    "soundex",
    "space",
    "sqrt",
    "stddev",
    "str",
    "substring",
    "sum",
    "sysdate",
    "tan",
    "time",
    "time_to_sec",
    "timediff",
    "timestamp",
    "to_days",
    "trim",
    "ucase",
    "unhex",
    "unix_timestamp",
    "upper",
    "utc_date",
    "utc_time",
    "utc_timestamp",
    "week",
    "weekday",
    "weekofyear",
    "year",
    "yearweek"
  ),

  columnTypes = Seq(
    "bigint",
    "binary($l)",
    "bit",
    "longblob",
    "bit",
    "char(1)",
    "longtext",
    "date",
    "double precision",
    "float",
    "integer",
    "nvarchar($l)",
    "longblob",
    "longtext",
    "nchar($l)",
    "nclob",
    "decimal($p,$s)",
    "nvarchar($l)",
    "real",
    "smallint",
    "time",
    "datetime(6)",
    "tinyint",
    "longblob",
    "longtext"
  )
)
// scalastyle:on
