/* Generated Code */
// scalastyle:off
package models.engine.rdbms

import models.engine.DatabaseEngine

object PostgreSQL extends DatabaseEngine(
  id = "postgres",
  name = "PostgreSQL",
  driverClass = "org.postgresql.Driver",
  exampleUrl = "jdbc:postgresql://hostname/dbname",

  builtInFunctions = Seq(
    "abs",
    "acos",
    "age",
    "ascii",
    "asin",
    "atan",
    "avg",
    "bit_length",
    "cast",
    "cbrt",
    "ceil",
    "char_length",
    "chr",
    "coalesce",
    "concat",
    "cos",
    "cot",
    "count",
    "current_database",
    "current_date",
    "current_schema",
    "current_time",
    "current_timestamp",
    "current_user",
    "date_trunc",
    "day",
    "degrees",
    "exp",
    "extract",
    "floor",
    "hour",
    "initcap",
    "length",
    "ln",
    "localtime",
    "localtimestamp",
    "locate",
    "log",
    "lower",
    "make_date",
    "make_interval",
    "make_time",
    "make_timestamp",
    "make_timestamptz",
    "max",
    "md5",
    "min",
    "minute",
    "mod",
    "month",
    "now",
    "nullif",
    "octet_length",
    "quote_ident",
    "quote_literal",
    "radians",
    "rand",
    "random",
    "round",
    "second",
    "session_user",
    "sign",
    "sin",
    "sqrt",
    "stddev",
    "str",
    "substr",
    "substring",
    "sum",
    "tan",
    "timeofday",
    "to_ascii",
    "to_char",
    "to_date",
    "to_number",
    "to_timestamp",
    "trim",
    "trunc",
    "upper",
    "user",
    "variance",
    "year"
  ),

  columnTypes = Seq(
    "int8",
    "bytea",
    "bool",
    "oid",
    "boolean",
    "char",
    "text",
    "date",
    "float8",
    "float4",
    "int4",
    "json",
    "nvarchar",
    "bytea",
    "text",
    "nchar",
    "nclob",
    "numeric",
    "nvarchar",
    "uuid",
    "real",
    "int2",
    "time",
    "timestamp",
    "int2",
    "bytea",
    "varchar"
  )
) {
  override val leftQuoteIdentifier = "\""
  override val rightQuoteIdentifier = "\""
  override val explain = Some((sql: String) => { "explain (costs, verbose, format json) " + sql })
  override val analyze = Some((sql: String) => { "explain (analyze, costs, verbose, buffers, format json) " + sql })
}
// scalastyle:on
